

INCLUDE(TribitsSetupStrongCompileWarnings)
INCLUDE(PrependCmndlineArgs)
INCLUDE(DualScopeAppendCmndlineArgs)




MACRO(TRIBITS_APPLY_WARNINGS_AS_ERROR_FLAGS_LANG LANG)
  PREPEND_CMNDLINE_ARGS(CMAKE_${LANG}_FLAGS
    "${${PROJECT_NAME}_WARNINGS_AS_ERRORS_FLAGS}")
  IF (${PROJECT_NAME}_VERBOSE_CONFIGURE)
    MESSAGE(STATUS "Setting up for ${LANG} warnings as errors just in this package ...")
    PRINT_VAR(CMAKE_${LANG}_FLAGS)
  ENDIF()
ENDMACRO()


MACRO(TRIBITS_SET_PACKAGE_LANGUAGE_FLAGS LANG)


  IF (${PACKAGE_NAME}_${LANG}_FLAGS)
    DUAL_SCOPE_APPEND_CMNDLINE_ARGS(CMAKE_${LANG}_FLAGS
      "${${PACKAGE_NAME}_${LANG}_FLAGS}")
  ENDIF()

  IF(${PROJECT_NAME}_VERBOSE_CONFIGURE)
    MESSAGE(STATUS "Adding strong ${LANG} warning flags \"${${LANG}_STRONG_COMPILE_WARNING_FLAGS}\"")
    PRINT_VAR(CMAKE_${LANG}_FLAGS)
  ENDIF()

ENDMACRO()


FUNCTION(TRIBITS_SETUP_ADD_PACKAGE_COMPILE_FLAGS)



  ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_C CMAKE_C_COMPILER_ID)
  IF (${PROJECT_NAME}_ENABLE_C)
    TRIBITS_SET_PACKAGE_LANGUAGE_FLAGS(C)
  ENDIF()


  ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_CXX CMAKE_CXX_COMPILER_ID)
  IF (${PROJECT_NAME}_ENABLE_CXX)
    TRIBITS_SET_PACKAGE_LANGUAGE_FLAGS(CXX)
  ENDIF()


  ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_Fortran)
  IF (${PROJECT_NAME}_ENABLE_Fortran)
    TRIBITS_SET_PACKAGE_LANGUAGE_FLAGS(Fortran)
  ENDIF()

ENDFUNCTION()














MACRO(TRIBITS_SETUP_COMPILER_FLAGS  PACKAGE_NAME_IN)


  IF (NOT PARSE_DISABLE_STRONG_WARNINGS AND NOT ${PACKAGE_NAME_IN}_DISABLE_STRONG_WARNINGS)
    TRIBITS_SETUP_STRONG_COMPILE_WARNINGS(${PARSE_ENABLE_SHADOWING_WARNINGS})
  ENDIF()


  ASSERT_DEFINED(PARSE_CLEANED)

  ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_C ${PROJECT_NAME}_ENABLE_C_DEBUG_COMPILE_FLAGS)
  IF (PARSE_CLEANED AND ${PROJECT_NAME}_ENABLE_STRONG_C_COMPILE_WARNINGS)
    TRIBITS_APPLY_WARNINGS_AS_ERROR_FLAGS_LANG(C)
  ENDIF()

  ASSERT_DEFINED(${PROJECT_NAME}_ENABLE_CXX ${PROJECT_NAME}_ENABLE_CXX_DEBUG_COMPILE_FLAGS)
  IF (PARSE_CLEANED AND ${PROJECT_NAME}_ENABLE_STRONG_CXX_COMPILE_WARNINGS)
    TRIBITS_APPLY_WARNINGS_AS_ERROR_FLAGS_LANG(CXX)
  ENDIF()

  TRIBITS_SETUP_ADD_PACKAGE_COMPILE_FLAGS()

  IF (${PROJECT_NAME}_VERBOSE_CONFIGURE)
    MESSAGE("Final compiler flags:")
    PRINT_VAR(CMAKE_CXX_FLAGS)
    PRINT_VAR(CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE})
    PRINT_VAR(CMAKE_C_FLAGS)
    PRINT_VAR(CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE})
    PRINT_VAR(CMAKE_Fortran_FLAGS)
    PRINT_VAR(CMAKE_Fortran_FLAGS_${CMAKE_BUILD_TYPE})
  ENDIF()

ENDMACRO()
