

INCLUDE(TribitsAddTestHelpers)


SET(TRIBITS_ADD_ADVANCED_TEST_MAX_NUM_TEST_CMND_IDX 19)



FUNCTION(TRIBITS_JOIN_EXEC_PROCESS_SET_ARGS  OUTPUT_STRING_VAR)
  SET(OUTPUT_STRING "")
  FOREACH(STRING_VAL_RAW ${ARGN})
    STRING(REGEX REPLACE "\"" "" STRING_VAL "${STRING_VAL_RAW}")
    IF (OUTPUT_STRING STREQUAL "")
      SET(OUTPUT_STRING "\"${STRING_VAL}\"")
    ELSE()
      SET(OUTPUT_STRING "${OUTPUT_STRING} \"${STRING_VAL}\"")
    ENDIF()
  ENDFOREACH()
  SET(${OUTPUT_STRING_VAR} "${OUTPUT_STRING}" PARENT_SCOPE)
ENDFUNCTION()



FUNCTION(TRIBITS_ADD_ADVANCED_TEST_UNITTEST_RESET)

  GLOBAL_SET(TRIBITS_ADD_ADVANCED_TEST_UNITTEST TRUE)

  GLOBAL_SET(TRIBITS_ADD_ADVANCED_TEST_NUM_CMNDS)

  FOREACH( TEST_CMND_IDX RANGE ${TRIBITS_ADD_ADVANCED_TEST_MAX_NUM_TEST_CMND_IDX})
    GLOBAL_SET(TRIBITS_ADD_ADVANCED_TEST_CMND_ARRAY_${TEST_CMND_IDX})
  ENDFOREACH()

ENDFUNCTION()
