

IF (F77_FUNC)
  SET(F77_BLAS_MANGLE_DEFAULT ${F77_FUNC})
ELSE()
  SET(F77_BLAS_MANGLE_DEFAULT "UNDEFINED")
ENDIF()
IF(WIN32 AND NOT CYGWIN)
  SET(F77_BLAS_MANGLE_DEFAULT "${F77_FUNC}")
ENDIF()



SET(F77_BLAS_MANGLE ${F77_BLAS_MANGLE_DEFAULT} CACHE STRING
  "Name mangling to call functions in the provided BLAS library")

MARK_AS_ADVANCED(F77_BLAS_MANGLE)
