
include(AppendSet)
include(AppendGlobalSet)
include(Split)
include(Join)
include(PrintVar)

FUNCTION(TRIBITS_ETI_TYPE_EXPANSION outvar first_list)
  IF (NOT "${first_list}" MATCHES "([^=]*)=(.*)")
    SET(${outvar} "TRIBITS_ETI_BAD_ARGUMENTS" PARENT_SCOPE)
    RETURN()
  ELSE()
    SET(label "${CMAKE_MATCH_1}")
    SET(tlist "${CMAKE_MATCH_2}")
  ENDIF()
  SPLIT("${tlist}" "\\|" tlist)
  IF ("${${outvar}}" STREQUAL "")
    SET(accumulate OFF)
  ELSE()
    SET(accumulate ON)
  ENDIF()
  LIST(LENGTH tlist tlist_len)
  IF (${ARGC} GREATER 2)
    TRIBITS_ETI_TYPE_EXPANSION(sub ${ARGN})
    FOREACH(t ${tlist})
      STRING(STRIP "${t}" t)
      SET(t "{${t}}")
      FOREACH(s ${sub})
        LIST(APPEND result "${label}=${t} ${s}")
      ENDFOREACH()
    ENDFOREACH()
  ELSE()
    FOREACH(t ${tlist})
      STRING(STRIP "${t}" t)
      SET(t "{${t}}")
      LIST(APPEND result "${label}=${t}")
    ENDFOREACH()
  ENDIF()
  IF (accumulate)
    SET(${outvar} "${${outvar}};${result}" PARENT_SCOPE)
  ELSE()
    SET(${outvar} "${result}"              PARENT_SCOPE)
  ENDIF()
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_EXPLODE fields inst outvar)
  foreach (field ${fields})
    IF(    "${inst}" MATCHES "( |^)${field}={([^{}$=]*)}( |$)")
      LIST(APPEND result "${CMAKE_MATCH_2}")
    ELSEIF("${inst}" MATCHES "( |^)${field}=([^{} $=]*)( |$)")
      LIST(APPEND result "${CMAKE_MATCH_2}")
    ELSEIF(NOT "${inst}" MATCHES "( |^)${field}=")
      LIST(APPEND result "TYPE-MISSING")
    ELSE()
      SET(result "TRIBITS_ETI_BAD_PARSE")
      BREAK()
    ENDIF()
  endforeach()
  JOIN(result "|" FALSE ${result})
  SET(${outvar} "${result}" PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_CHECK_EXCLUSION processed_excludes processed_inst excluded)
  SPLIT("${processed_inst}" "\\|" processed_inst)
  LIST(LENGTH processed_inst numfields)
  MATH(EXPR NFm1 "${numfields}-1")
  SET(${excluded} OFF PARENT_SCOPE)
  list(LENGTH processed_excludes numexcl)
  FOREACH(excl ${processed_excludes})
    SPLIT(${excl} "\\|" excl)
    LIST(LENGTH excl excp_len)
    IF(${excp_len} EQUAL ${numfields})
      SET(lcltest ON)
      FOREACH(i RANGE 0 ${NFm1})
        LIST(GET processed_inst ${i} f)
        LIST(GET excl           ${i} e)
        IF (NOT "${f}" STREQUAL "TYPE-MISSING" AND NOT "${f}" MATCHES "${e}")
          SET(lcltest OFF)
          BREAK()
        ENDIF()
      ENDFOREACH()
      IF(lcltest)
        SET(${excluded} ON PARENT_SCOPE)
        IF (${PROJECT}_VERBOSE_CONFIGURE)
          MESSAGE(STATUS "-- Instantiation excluded by ${excl}")
        ENDIF()
        RETURN()
      ENDIF()
    ENDIF()
  ENDFOREACH()
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_INDEX_MACRO_FIELDS etifields macrofields indexvar)
  FOREACH(mf ${macrofields})
    STRING(STRIP "${mf}" mf)
    LIST(FIND etifields ${mf} ind)
    IF(${ind} EQUAL -1)
      MESSAGE(FATAL_ERROR "Macro variable ${mf} not found in list of fields: ${etifields}")
    ENDIF()
    LIST(APPEND inds ${ind})
  ENDFOREACH()
  SET(${indexvar} ${inds} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_BUILD_MACRO_STRING macroname tuplelist outvar)
  SET(str "#define ${macroname}(INSTMACRO)")
  FOREACH(tuple ${tuplelist})
    STRING(REPLACE "|" " , " tuple "${tuple}")
    SET(str "${str}\\\n\tINSTMACRO( ${tuple} )")
  ENDFOREACH()
  SET(str "${str}\n")
  SET(${outvar} ${str} PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(TRIBITS_ADD_ETI_INSTANTIATIONS PACKAGE)
  IF(${PROJECT_NAME}_VERBOSE_CONFIGURE)
    MESSAGE(STATUS "Adding instantiations to ${PACKAGE} library set...")
  ENDIF()
  APPEND_GLOBAL_SET(${PACKAGE}_ETI_LIBRARYSET ${ARGN})
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_MANGLE_SYMBOL
         mangledvar
         input)
  SET(newvar "${input}")
  STRING(REPLACE "::" "_" newvar "${newvar}")
  STRING(REPLACE ","  "_" newvar "${newvar}")
  SET(num_brackets 0)
  WHILE("${newvar}" MATCHES "(.*)<([^<>]*)>(.*)")
    SET(newvar "${CMAKE_MATCH_1}${num_brackets}${CMAKE_MATCH_2}${num_brackets}${CMAKE_MATCH_3}")
    MATH(EXPR num_brackets "${num_brackets}+1")
  ENDWHILE()
  STRING(REPLACE " "  "" newvar "${newvar}")
  SET(${mangledvar} "${newvar}" PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_MANGLE_SYMBOL_AUGMENT_MACRO
         typedefvar
         symbolvar
         manglistvar)
  SET(oldsymbol "${${symbolvar}}")
  IF(NOT "${oldsymbol}" MATCHES "::|[<>, ]")
    RETURN()
  ENDIF()
  TRIBITS_ETI_MANGLE_SYMBOL(newsymbol "${oldsymbol}")
  SET(${symbolvar} "${newsymbol}" PARENT_SCOPE)
  LIST(FIND ${manglistvar} ${newsymbol} already_mangled)
  IF(${already_mangled} EQUAL -1)
    LIST(APPEND ${manglistvar} ${newsymbol})
    SET(${manglistvar} ${${manglistvar}} PARENT_SCOPE)
    LIST(APPEND ${typedefvar}  "typedef ${oldsymbol} ${newsymbol}")
    SET(${typedefvar}  ${${typedefvar}}  PARENT_SCOPE)
  ENDIF()
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_GENERATE_MACROS etifields etisetvar etiexcludelist manglinglistvar typedeflistvar)
  SET(manglinglist  "${${manglinglistvar}}")
  SET(typedeflist   "${${typedeflistvar}}")
  SPLIT("${etifields}" "\\|" etifields)
  IF(${PROJECT}_VERBOSE_CONFIGURE)
    MESSAGE(STATUS "ETI fields: ${etifields}")
    MESSAGE(STATUS "ETI set: ${etisetvar}")
    MESSAGE(STATUS "ETI excludes: ${etiexcludelist}")
  ENDIF()
  MATH(EXPR num_macros "(${ARGC}-5)/2")
  IF(${num_macros} EQUAL 0)
    RETURN()
  ENDIF()
  FOREACH(m RANGE 1 ${num_macros})
    MATH(EXPR m2   "(${m}-1)*2")
    MATH(EXPR m2p1 "${m2}+1")
    LIST(GET ARGN ${m2}   macroarg)
    LIST(GET ARGN ${m2p1} macrovar${m})
    STRING(REGEX REPLACE "^(.*)\\(.*"     "\\1" macroname${m} ${macroarg})
    STRING(REGEX REPLACE "^.*\\((.*)\\)$" "\\1" macrofields${m} ${macroarg})
    SPLIT("${macrofields${m}}" "," macrofields)
    TRIBITS_ETI_INDEX_MACRO_FIELDS("${etifields}" "${macrofields}" macroindex${m})
    IF(${PROJECT}_VERBOSE_CONFIGURE)
      MESSAGE(STATUS "Parsed macro ${macroname${m}}(${macrofields${m}}) into variable ${macrovar${m}} (index list ${macroindex${m}})")
    ENDIF()
  ENDFOREACH()
  FOREACH(excl ${etiexcludelist})
    TRIBITS_ETI_EXPLODE("${etifields}" "${excl}" e_excl)
    IF("${e_excl}" STREQUAL "TRIBITS_ETI_BAD_PARSE")
      MESSAGE(FATAL_ERROR "TRIBITS_GENERATE_ETI_MACROS: exclusion did not parse: ${excl}")
    ENDIF()
    LIST(APPEND processed_excludes "${e_excl}")
  ENDFOREACH()
  LIST(LENGTH etifields numfields)
  MATH(EXPR NFm1 "${numfields}-1")
  FOREACH(inst ${etisetvar})
    IF (${PROJECT}_VERBOSE_CONFIGURE)
      MESSAGE(STATUS "Processing instantiation: ${inst}") # comment
    ENDIF()
    TRIBITS_ETI_EXPLODE("${etifields}" "${inst}" tmp)
    IF("${tmp}" STREQUAL "TRIBITS_ETI_BAD_PARSE")
      MESSAGE(FATAL_ERROR "TRIBITS_GENERATE_ETI_MACROS: instantiation did not parse: ${inst}")
    ELSE()
      SET(inst "${tmp}")
    ENDIF()
    TRIBITS_ETI_CHECK_EXCLUSION("${processed_excludes}" "${inst}" excluded)
    IF(NOT excluded)
      SPLIT("${inst}" "\\|" inst)
      FOREACH(m RANGE 1 ${num_macros})
        SET(tuple "")
        FOREACH(ind ${macroindex${m}})
          LIST(GET inst ${ind} t)
          IF("${t}" STREQUAL "TYPE-MISSING")
            SET(tuple "SKIP-TUPLE")
            BREAK()
          ENDIF()
          TRIBITS_ETI_MANGLE_SYMBOL_AUGMENT_MACRO(typedeflist t manglinglist)
          LIST(APPEND tuple ${t})
        ENDFOREACH()
        IF(NOT "${tuple}" STREQUAL "SKIP-TUPLE")
          JOIN(tuple "|" FALSE "${tuple}")
          LIST(APPEND macrotuples${m} ${tuple})
        ENDIF()
      ENDFOREACH()
    ENDIF()
  ENDFOREACH()
  FOREACH(m RANGE 1 ${num_macros})
    IF(DEFINED macrotuples${m})
      LIST(REMOVE_DUPLICATES macrotuples${m})
    ENDIF()
  ENDFOREACH()
  FOREACH(m RANGE 1 ${num_macros})
    TRIBITS_ETI_BUILD_MACRO_STRING("${macroname${m}}" "${macrotuples${m}}" mac)
    SET(${macrovar${m}} "${mac}" PARENT_SCOPE)
  ENDFOREACH()
  SET(${manglinglistvar} ${manglinglist} PARENT_SCOPE)
  SET(${typedeflistvar}  ${typedeflist}  PARENT_SCOPE)
ENDFUNCTION()

FUNCTION(TRIBITS_ETI_GENERATE_TYPEDEF_MACRO outputvar macroname typedeflist)
  SET(mac "#define ${macroname}() ")
  FOREACH(td ${typedeflist})
    SET(mac "${mac} \\\n\t${td};")
  ENDFOREACH()
  SET(${outputvar} "${mac}" PARENT_SCOPE)
ENDFUNCTION()
