

IF (${PROJECT_NAME}_VERBOSE_CONFIGURE)

FUNCTION(TRIBITS_VERBOSE_PRINT_VAR VARIBLE_NAME)
  MESSAGE("-- " "${VARIBLE_NAME}='${${VARIBLE_NAME}}'")
ENDFUNCTION()


ELSE() # ${PROJECT_NAME}_VERBOSE_CONFIGURE


FUNCTION(TRIBITS_VERBOSE_PRINT_VAR VARIBLE_NAME)
ENDFUNCTION()


ENDIF() # ${PROJECT_NAME}_VERBOSE_CONFIGURE
