
INCLUDE(ConcatStrings)
INCLUDE(PrintVar)

FUNCTION(APPEND_STRING_VAR STRING_VAR_OUT)
  CONCAT_STRINGS( STRING_VAR "${${STRING_VAR_OUT}}" ${ARGN} )
  SET(${STRING_VAR_OUT} "${STRING_VAR}" PARENT_SCOPE)
ENDFUNCTION()


FUNCTION(APPEND_STRING_VAR_EXT  STRING_VAR_OUT  STRING_TO_APPEND)
  SET(STRING_VAR "${${STRING_VAR_OUT}}${STRING_TO_APPEND}")
  SET(${STRING_VAR_OUT} "${STRING_VAR}" PARENT_SCOPE)
ENDFUNCTION()
