


FUNCTION(FIND_LIST_ELEMENT LIST_NAME ELEMENT_VAL ELEMENT_FOUND_OUT)
  LIST(FIND ${LIST_NAME} ${ELEMENT_VAL} ELEMENT_IDX)
  IF (ELEMENT_IDX EQUAL -1)
    SET(ELEMENT_FOUND FALSE)
  ELSE()
    SET(ELEMENT_FOUND TRUE)
  ENDIF()
  SET(${ELEMENT_FOUND_OUT} ${ELEMENT_FOUND} PARENT_SCOPE)
ENDFUNCTION()
