
FUNCTION(GET_CURRENT_LIST_DIR output_variable)
  IF(NOT DEFINED CMAKE_CURRENT_LIST_DIR)
    GET_FILENAME_COMPONENT(CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
  ENDIF()
  SET(${output_variable} "${CMAKE_CURRENT_LIST_DIR}" PARENT_SCOPE)
ENDFUNCTION()
