
INCLUDE(PrintVar)
INCLUDE(GlobalSet)

FUNCTION(MESSAGE_WRAPPER)
  IF (MESSAGE_WRAPPER_UNIT_TEST_MODE)
    GLOBAL_SET(MESSAGE_WRAPPER_INPUT "${MESSAGE_WRAPPER_INPUT}" ${ARGN})
  ELSE()
    MESSAGE(${ARGN})
  ENDIF()
ENDFUNCTION()

