

FUNCTION(MULTILINE_SET VARAIBLE_NAME)

  SET(MULTILINE_SET_LOCAL_STR "")

  FOREACH(LINE_STR ${ARGN})
    SET(MULTILINE_SET_LOCAL_STR "${MULTILINE_SET_LOCAL_STR}${LINE_STR}")
  ENDFOREACH()

  SET(${VARAIBLE_NAME} "${MULTILINE_SET_LOCAL_STR}" PARENT_SCOPE)

ENDFUNCTION()
