
INCLUDE(AssertDefined)
INCLUDE(AppendStringVarWithSep)

FUNCTION(PRINT_NONEMPTY_VAR_WITH_SPACES  VARIBLE_NAME  PRINTED_VAR_OUT)
  ASSERT_DEFINED(VARIBLE_NAME)
  IF (NOT "${${VARIBLE_NAME}}" STREQUAL "")
    STRING(REPLACE ";" " " OUTSTR "${${VARIBLE_NAME}}")
    MESSAGE("-- ${VARIBLE_NAME}: ${OUTSTR}")
    SET(${PRINTED_VAR_OUT} TRUE PARENT_SCOPE)
  ENDIF()
ENDFUNCTION()
